package com.projetogs.mylibrary.repository;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.MongoDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import com.projetogs.mylibrary.config.MongoTestConfig;
import com.projetogs.mylibrary.entities.User;

@SpringBootTest(properties = {
        "api.security.token.secret=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
})
@Testcontainers
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RepositoryTest {

    @Container
    static MongoDBContainer mongoDBContainer = new MongoDBContainer("mongo:7");

    @DynamicPropertySource
    static void setProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.data.mongodb.uri", mongoDBContainer::getReplicaSetUrl);

        registry.add("spring.data.mongodb.database", () -> "mylibrarytest");
    }

    @Autowired
    private BookRepository bookRepository;

    @Autowired
    private UserRepository userRepository;

    private static String savedUserId;

    @BeforeEach
    void setUp() {
        bookRepository.deleteAll();
        userRepository.deleteAll();

        User user = new User("Test User", "test@email.com", "Senha@123");
        User savedUser = userRepository.save(user);
        savedUserId = savedUser.getId();
    }

    // RF01 - Cadastro de Usuários

    @Test
    @Order(1)
    @DisplayName("RF01 - Should save and retrieve the user by email")
    void shouldSaveAndRetrieveUserByEmail() {
        Optional<User> found = userRepository.findByEmail("test@email.com");

        assertTrue(found.isPresent(), "User should be found by email");
        assertEquals("Test User", found.get().getName());
        assertEquals("test@email.com", found.get().getEmail());
    }

    @Test
    @Order(2)
    @DisplayName("RF02 - Should return an empty result for a non-existent email address")
    void shouldReturnEmptyResultForNonExistentEmail() {
        Optional<User> found = userRepository.findByEmail("naoexiste@email.com");
        assertTrue(found.isEmpty(), "Should not find any users with non-existent email");
    }

    @Test
    @Order(3)
    @DisplayName("RF03 - Should persist the ID automatically generated by MongoDB")
    void shouldPersistAutomaticallyGeneratedId() {
        Optional<User> found = userRepository.findByEmail("test@email.com");

        assertTrue(found.isPresent());
        assertNotNull(found.get().getId(), "ID should be automatically generated");
        assertFalse(found.get().getId().isBlank());
    }
}
