package com.projetogs.mylibrary.repository;


import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;

import com.projetogs.mylibrary.config.MongoTestConfig;
import com.projetogs.mylibrary.entities.Book;
import com.projetogs.mylibrary.entities.User;
import com.projetogs.mylibrary.enums.ReadingStatus;


/**
 Testes de repositório. Infraestrutura: TestContainers (Sem Mocks) 
**/
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RepositoryTest extends MongoTestConfig {
    
    @Autowired
    private BookRepository bookRepository;

    @Autowired
    private UserRepository userRepository;

    private static String savedUserId;

    @BeforeEach
    void setUp() {
        bookRepository.deleteAll();
        userRepository.deleteAll();

        User user = new User("Test User", "test@email.com", "Senha@123");
        User savedUser = userRepository.save(user);
        savedUserId = savedUser.getId();
    }

    // Helper
    private Book criarLivro(String title, String author, String genre, ReadingStatus status){
        Book book = new Book();
        book.setTitle(title);
        book.setAuthor(author);
        book.setGenre(genre);
        book.setStatus(status);
        book.setUserId(savedUserId);
        return book;
    }

    // RF01 - Cadastro de Usuários

    @Test
    @Order(1)
    @DisplayName("RF01 - Should save and retrieve the user by email")
    void shouldSaveAndRetrieveUserByEmail(){
        Optional<User> found = userRepository.findByEmail("test@email.com");

        assertTrue(found.isPresent(), "User should be found by email");
        assertEquals("Test User", found.get().getName());
        assertEquals("test@email.com", found.get().getEmail());
    }

    @Test
    @Order(2)
    @DisplayName("RF01 - Should return an empty result for a non-existent email address")
    void shouldReturnEmptyResultForNonExistentEmail(){
        Optional<User> found = userRepository.findByEmail("naoexiste@email.com");
        assertTrue(found.isEmpty(), "Should not find any users with non-existent email");
    }

    @Test
    @Order(3)
    @DisplayName("RF01 - Should persist the ID automatically generated by MongoDB")
    void shouldPersistAutomaticallyGeneratedId(){
        Optional<User> found = userRepository.findByEmail("test@email.com");

        assertTrue(found.isPresent());
        assertNotNull(found.get().getId(), "ID should be automatically generated");
        assertFalse(found.get().getId().isBlank());
    }

    // RF02 - CRUD de Livros

    @Test
    @Order(4)
    @DisplayName("RF02 - Should save and retrieve book by ID")
    void shouldSaveAndRetrieveBookById(){
        Book book = criarLivro("Clean Code", "Robert Martin", "Tecnologia", ReadingStatus.READ);
        Book saved = bookRepository.save(book);

        Optional<Book> found = bookRepository.findById(saved.getId());

        assertTrue(found.isPresent());
        assertEquals("Clean Code", found.get().getTitle());
        assertEquals("Robert Martin", found.get().getAuthor());
        assertEquals(savedUserId, found.get().getUserId());
    }

    @Test
    @Order(5)
    @DisplayName("RF02 - Should list all user Books")
    void shoudListAllUserBooks(){
        bookRepository.save(criarLivro("Clean Code", "Robert Martin", "Tecnologia", ReadingStatus.READ));
        bookRepository.save(criarLivro("1984", "George Orwell", "Ficção", ReadingStatus.READING));
        bookRepository.save(criarLivro("Dom Casmurro", "Machado de Assis", "Literatura", ReadingStatus.WANNA_READ));
 
        List<Book> books = bookRepository.findByUserId(savedUserId);
 
        assertEquals(3, books.size(), "Should return exactly 3 of the user's books");
    }

}
