package com.projetogs.mylibrary.repository;


import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.beans.factory.annotation.Autowired;

import com.projetogs.mylibrary.config.MongoTestConfig;
import com.projetogs.mylibrary.entities.User;


/**
 Testes de repositório. Infraestrutura: TestContainers (Sem Mocks) 
**/
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RepositoryTest extends MongoTestConfig {
    
    @Autowired
    private BookRepository bookRepository;

    @Autowired
    private UserRepository userRepository;

    private static String savedUserId;

    @BeforeEach
    void setUp() {
        bookRepository.deleteAll();
        userRepository.deleteAll();

        User user = new User("Test User", "test@email.com", "Senha@123");
        User savedUser = userRepository.save(user);
        savedUserId = savedUser.getId();
    }

    // RF01 - Cadastro de Usuários

    @Test
    @Order(1)
    @DisplayName("RF01 - Should save and retrieve the user by email")
    void shouldSaveAndRetrieveUserByEmail(){
        Optional<User> found = userRepository.findByEmail("test@email.com");

        assertTrue(found.isPresent(), "User should be found by email");
        assertEquals("Test User", found.get().getName());
        assertEquals("test@email.com", found.get().getEmail());
    }

    @Test
    @Order(2)
    @DisplayName("RF01 - Should return an empty result for a non-existent email address")
    void shouldReturnEmptyResultForNonExistentEmail(){
        Optional<User> found = userRepository.findByEmail("naoexiste@email.com");
        assertTrue(found.isEmpty(), "Should not find any users with non-existent email");
    }

    @Test
    @Order(3)
    @DisplayName("RF01 - Should persist the ID automatically generated by MongoDB")
    void shouldPersistAutomaticallyGeneratedId(){
        Optional<User> found = userRepository.findByEmail("test@email.com");

        assertTrue(found.isPresent());
        assertNotNull(found.get().getId(), "ID should be automatically generated");
        assertFalse(found.get().getId().isBlank());
    }
}
